apiVersion: cubestore.io/v1alpha1
kind: CubestoreRouter
metadata:
  name: demo
  namespace: cube-operator-demo
spec:
  namespace: cube-operator-demo
  selector:
    app: cube-router
  routerPort: 3030
  healthPath: /router/status
  electionStrategy: lease
  roleConfigMapName: cube-router-demo-router-role-state
  metaStore:
    address: cubestore-metastore.cube-operator-demo.svc:9999
  storage:
    dataPVC: worker-data
  stateStore:
    type: redis
    secretRef:
      name: cube-router-demo-lease-store
      namespace: cube-operator-demo
