apiVersion: v1
kind: ServiceAccount
metadata:
  name: cube-operator
  namespace: cube-operator-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cube-operator
  namespace: cube-operator-demo
rules:
  - apiGroups: ["" ]
    resources: ["pods", "pods/status", "events", "configmaps", "services", "endpoints", "secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["cubestore.io"]
    resources: ["cubestorerouters", "cubestorerouters/status", "cubestorerouters/finalizers", "cubeclusters", "cubeclusters/status", "cubeclusters/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cube-operator
  namespace: cube-operator-demo
subjects:
  - kind: ServiceAccount
    name: cube-operator
    namespace: cube-operator-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cube-operator
