apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cubestore-metastore
  labels:
    app.kubernetes.io/name: cubestore-metastore
    app.kubernetes.io/component: metastore
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cubestore-metastore
      app.kubernetes.io/component: metastore
