apiVersion: v1
kind: Service
metadata:
  name: cubestore-metastore
  labels:
    app.kubernetes.io/name: cubestore-metastore
    app.kubernetes.io/component: metastore
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  selector:
    app.kubernetes.io/name: cubestore-metastore
    app.kubernetes.io/component: metastore
  ports:
    - name: metastore
      port: 9999
      targetPort: metastore
      protocol: TCP
